update test and remove ganachi cli yaml

diff --git a/.github/workflows/tests.yaml b/.github/workflows/tests.yaml
--- a/.github/workflows/tests.yaml
+++ b/.github/workflows/tests.yaml
@@ -23,34 +23,23 @@ jobs:
         uses: actions/setup-node@v4
         with:
           node-version: 18.12.1
-
-      - name: Install Dependencies
-        run: yarn --immutable
-
+          
       - name: Wait for Ganache to be ready
         run: |
           echo "Waiting for Ganache to be ready..."
-          for i in `seq 1 30`; do
+          for i in {1..30}; do
             if curl -s -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://127.0.0.1:8545 > /dev/null; then
               echo "Ganache is running"
-              break
+              exit 0
             fi
             echo "Waiting for Ganache to be ready... attempt $i"
             sleep 1
           done
-          if ! curl -s -X POST --data '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}' http://127.0.0.1:8545 > /dev/null; then
-            echo "Ganache failed to start"
-            exit 1
-          fi
+          echo "Ganache failed to start"
+          exit 1
 
-      - name: Enable Corepack
-        run: corepack enable
-
-      - name: Run Tests
-        run: yarn run test
-
-      - name: Run Lint
-        run: yarn run lint
-
-      - name: Run Type Check
-        run: yarn run typeCheck
+      - run: corepack enable
+      - run: yarn --immutable
+      - run: yarn run test
+      - run: yarn run lint
+      - run: yarn run typeCheck
